### PR TITLE
add support for 3 kasm sessions in docker-compose.yml

### PR DESCRIPTION
**Pull request by matthewstorch**
Here is the change that allows 3 kasm sessions.

### CODE REVIEW

**Review by capsulecorplab — CHANGES_REQUESTED** [review]
I get a "bind source path doesn't exist" error. Should probably add a `kasm_user2` and `kasm_user3` directory (containing a `_README` similar to https://github.com/mdrs-community/mdrs-workspace-image/tree/main/kasm_user) so that there's a starting directory to bind to 
Screenshot from 2024-04-04 07-29-54

**Comment by capsulecorplab** [comment]
Just tried manually creating the `kasm_user2` and `kasm_user3` directories. I'm getting a "secured connection failed" error for the other two kasm sessions 
Screenshot from 2024-04-04 07-53-35
Screenshot from 2024-04-04 07-53-43
Screenshot from 2024-04-04 07-53-48

**Comment by matthewstorch** [comment]
I added the additional kasm_user dirs as requested.

**Comment by capsulecorplab** [comment]
I have no idea what changed, but I'm able to run all 3 kasm users now! :sweat_smile: 
Screenshot from 2024-04-09 15-58-39
Screenshot from 2024-04-09 15-57-52
Screenshot from 2024-04-09 15-58-19

**Pull request merged**
